#!/bin/bash

hive -e "
with all_events AS (
    select
        wiki,
        case
            when event.performer.user_id is null then 'anonymous'
            -- TODO: after the user_edit_count_bucket producer is fully migrated, probably in
            -- wmf/1.36.0-wmf.29, we can remove transitional logic and trust the bucket label.
            when event.performer.user_edit_count_bucket is not null then event.performer.user_edit_count_bucket
            when event.performer.user_edit_count >= 1000 then '1000+ edits'
            when event.performer.user_edit_count >= 100 then '100-999 edits'
            when event.performer.user_edit_count >= 5 then '5-99 edits'
            when event.performer.user_edit_count >= 1 then '1-4 edits'
            when event.performer.user_edit_count = 0 then '0 edits'
            else 'unknown'
        end as edit_count_bucket
    from
        event.TemplateWizard
    where
        event.action = 'launch'
        and year = cast(split('$1', '-')[0] as int)
        and month = cast(split('$1', '-')[1] as int)
        and day = cast(split('$1', '-')[2] as int)
)

select
    '$1' as \`date\`,
    wiki,
    edit_count_bucket,
    count(*) as template_wizard_opens
from
    bucketed_events
group by
    wiki,
    edit_count_bucket;
" 2> /dev/null | grep -v parquet.hadoop
