#!/bin/bash
hive -e "
WITH all_events AS (
    SELECT
        wiki,
        event.user_editcount,
        event.user_id
    FROM
        event.VisualEditorFeatureUse
    WHERE
        event.feature = 'transclusion'
        AND event.action LIKE 'window-open-%'
        -- FIXME: How can we filter out oversampled events?
        AND year = cast(split('$1', '-')[0] as int)
        AND month = cast(split('$1', '-')[1] as int)
        AND day = cast(split('$1', '-')[2] as int)
),

bucketed_events AS (
    SELECT
        wiki,
        CASE WHEN user_id = 0 THEN 'anonymous'
            WHEN user_editcount > 10000 THEN 'over10k'
            WHEN user_editcount > 1000 THEN 'over1k'
            WHEN user_editcount > 100 THEN 'over100'
            WHEN user_editcount > 10 THEN 'over10'
            ELSE 'under11'
        END edit_count_bucket
    FROM
        all_events
)

SELECT
    '$1' AS \`date\`,
    wiki,
    edit_count_bucket,
    -- Compensate for sampling by multiplying by 1 / 6.25% = 16
    COUNT(*) * 16 as template_dialog_opens
FROM
    bucketed_events
GROUP BY
    wiki,
    edit_count_bucket;
" 2> /dev/null | grep -v parquet.hadoop
