databases:
    flow:
        auto_find_db_shard: true
        use_x1: true
        creds_file: /etc/mysql/conf.d/stats-research-client.cnf
        db: flowdb

defaults:
    db: flow

reports:
    active-boards:
        granularity: weeks
        starts: 2009-11-08
    active-topics:
        granularity: weeks
        starts: 2009-11-08
    created-topics:
        granularity: weeks
        starts: 2009-11-08
    messages-posted:
        granularity: weeks
        starts: 2009-11-08
    moderation-actions:
        granularity: weeks
        starts: 2009-11-08
    unique-users:
        granularity: weeks
        starts: 2009-11-08
