#!/bin/bash
hive -e "

-- Get all CodeMirror usage events for the day.
with all_events as (
    select
        wiki,
        event.editor,
        event.enabled,
        event.session_token,
        event.edit_start_ts_ms,
        seqid
    from
        event.CodeMirrorUsage
    where
        year = cast(split('$1', '-')[0] as int)
        and month = cast(split('$1', '-')[1] as int)
        and day = cast(split('$1', '-')[2] as int)
),

-- Group by edit session.
grouped_sessions as (
    select
        wiki,
        editor,
        enabled,
        row_number()
            over (
                partition by
                    wiki, session_token, edit_start_ts_ms
                order by
                    seqid desc
            )
            as row
    from
        all_events
),

-- Take the latest event.
latest_events as (
    select
        wiki,
        editor,
        enabled
    from
        grouped_sessions
    where
        row = 1
)

-- Sum each possible combination of attributes.
select
    '$1' as report_date,
    wiki,
    sum(case when editor = 'wikitext' and enabled = true then 1 else 0 end) as enabled_in_wikitext_session,
    sum(case when editor = 'wikitext' and enabled = false then 1 else 0 end) as disabled_in_wikitext_session,
    sum(case when editor = 'wikitext-2017' and enabled = true then 1 else 0 end) as enabled_in_wikitext_2017_session,
    sum(case when editor = 'wikitext-2017' and enabled = false then 1 else 0 end) as disabled_in_wikitext_2017_session
from
    latest_events
group by
    wiki;
" 2> /dev/null | grep -v parquet.hadoop
