#!/bin/bash
hive -e "
    SELECT
        '$1' AS report_date,
        wiki_db,
        SUM(IF(network_origin='wikimedia_labs', edit_count, 0)) AS wmcs_edits
    FROM wmf.editors_daily
    WHERE
        month = substr('$1', 1, 7)
    GROUP BY
        wiki_db
    ORDER BY
        wiki_db
    LIMIT 10000
    ;
" 2> /dev/null | grep -v parquet.hadoop
