#!/bin/bash
hive -e "
    SELECT
        '$1' AS date,
        wiki_db,
        SUM(IF(network_origin='wikimedia_labs', edit_count, 0)) AS wmcs_edits,
        SUM(edit_count) AS total_edits
        ROUND(SUM(IF(network_origin='wikimedia_labs', edit_count, 0)) / SUM(edit_count), 3) AS wmcs_percent
    FROM wmf.editors_daily
    WHERE
        MONTH = substr('$1', 1, 7)
    GROUP BY
        wiki_db
    ORDER BY
        wiki_db
    LIMIT 10000
    ;
" 2> /dev/null | grep -v parquet.hadoop