databases:
    mediawiki:
        auto_find_db_shard: true
        wiki_db_placeholder: wiki_db
        creds_file: /etc/mysql/conf.d/stats-research-client.cnf
defaults:
    db: mediawiki

reports:
    flow_beta:
        granularity: days
        starts: 2016-01-19
        explode_by:
            wiki_db: testwiki, mediawikiwiki, bswiki, cawiki, frwiki, frwikiquote, frwikisource, frwikivoyage, nowiki, urwiki, zhwiki, wikidatawiki, specieswiki, outreachwiki

