#!/bin/bash
# Lua can be used to enrich file pages with structured data (Wikidata or mediainfo)
# This report counts how many pages are enriched this way, excluding sitelinks
# NOTE: As of 2019-12, the majority of the usage counted here points to Wikidata

MONTH=$(echo $1 | cut -c1-7)
hive -e "
 SELECT '$1' AS date,
        COUNT(DISTINCT page_id) AS usage_count

        -- page excludes deleted pages (which are in archive)
   FROM wmf_raw.mediawiki_page
            INNER JOIN
        wmf_raw.mediawiki_wbc_entity_usage  ON eu_page_id = page_id

        -- only include file pages and non-sitelink usage
  WHERE page_namespace = 6
    AND eu_aspect != 'S'
    AND wmf_raw.mediawiki_page.wiki_db = 'commonswiki'
    AND wmf_raw.mediawiki_wbc_entity_usage.wiki_db = 'commonswiki'
    AND wmf_raw.mediawiki_page.snapshot = '$MONTH'
    AND wmf_raw.mediawiki_wbc_entity_usage.snapshot = '$MONTH'
;
" 2> /dev/null | grep -v parquet.hadoop
