#!/bin/bash
# see https://phabricator.wikimedia.org/T247417
# number of total 'non-text' files being used on content pages of other wikimedia projects
# by "other" wikimedia projects, we mean all wikis except for commons

MONTH=$(echo $1 | cut -c1-7)
hive -e "


use wmf_raw;
set hive.mapred.mode=nonstrict;

WITH

    wiki_content_namespaces as (
        SELECT
            dbname,
            namespace
        FROM
            mediawiki_project_namespace_map
        WHERE
            namespace_is_content = 1
            AND snapshot = '${MONTH}'
    ),

    imagelinks_commons_files as (
        SELECT
            COUNT(DISTINCT il_to) AS num_uses_of_commons_files_on_content_pages
        FROM
            mediawiki_imagelinks as m
            INNER JOIN wiki_content_namespaces AS ns
                ON (ns.namespace = m.il_from_namespace AND ns.dbname = m.wiki_db)
        WHERE
            m.snapshot = '${MONTH}'
            AND m.wiki_db <> 'commonswiki'
    ),

    page_history_commons_files as (
        SELECT
            COUNT(DISTINCT page_id) AS num_commons_files
        FROM
            wmf.mediawiki_page_history
        WHERE
            snapshot='${MONTH}'
            AND NOT page_is_redirect
            AND NOT page_is_deleted
            AND page_namespace = 6
            AND wiki_db = 'commonswiki'
    )

    SELECT
        '$1' as date,
        num_uses_of_commons_files_on_content_pages,
        num_commons_files,
        (num_uses_of_commons_files_on_content_pages/num_commons_files) as ratio
    FROM
        page_history_commons_files, imagelinks_commons_files
    ;



" 2> /dev/null | grep -v parquet.hadoop

