#!/bin/bash
# MediaInfo is a type of structured data entity, stored in a slot by mediawiki.
# This report counts pages which have a non-empty MediaInfo slot in their latest revision

MONTH=$(echo $1 | cut -c1-7)
hive -e "
 SELECT '$1' AS date,
        COUNT(DISTINCT page_id) AS mediainfo_slot_count

        -- page excludes deleted pages (which are in archive)
   FROM wmf_raw.mediawiki_page
            -- joining on page_latest - we only care about most recent
            INNER JOIN
        wmf_raw.mediawiki_slots         ON slot_revision_id = page_latest
            -- mediainfo slot must contain actual content
            INNER JOIN
        wmf_raw.mediawiki_content       ON slot_content_id = content_id
                                        AND content_size > 122
            INNER JOIN
        wmf_raw.mediawiki_slot_roles    ON role_id = slot_role_id
                                        AND role_name = 'mediainfo'

  WHERE mediawiki_page.wiki_db = 'commonswiki'
    AND mediawiki_slots.wiki_db = 'commonswiki'
    AND mediawiki_content.wiki_db = 'commonswiki'
    AND mediawiki_slot_roles.wiki_db = 'commonswiki'
    AND mediawiki_page.snapshot = '$MONTH'
    AND mediawiki_slots.snapshot = '$MONTH'
    AND mediawiki_content.snapshot = '$MONTH'
    AND mediawiki_slot_roles.snapshot = '$MONTH'
;
" 2> /dev/null | grep -v parquet.hadoop
