#!/bin/bash
hive -e "
WITH numbered AS (
    SELECT
        event.arch AS event_arch,
        ROW_NUMBER() OVER (
            PARTITION BY wiki
            ORDER BY dt DESC
        ) AS row_num
    FROM
        event_sanitized.mediawikipingback
    WHERE
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0'), 'T', LPAD(hour, 2, '0'))  >= '2017-03-29T17' AND
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2' AND
        (event.\`database\` LIKE 'mysql%' OR NOT (
            event.MediaWiki LIKE '1.31.0%' OR
            event.MediaWiki = '1.32.0-alpha'
        )) AND
        event.arch IS NOT NULL
)
SELECT
    '$1' AS date,
    SUM(IF(event_arch = 32, 1, 0)) AS \`32\`,
    SUM(IF(event_arch = 64, 1, 0)) AS \`64\`,
    SUM(IF(event_arch != 32 AND event_arch != 64, 1, 0)) AS \`Other\`
FROM numbered
WHERE row_num = 1
;
" 2> /dev/null | grep -v parquet.hadoop
