#!/bin/bash
hive -e "
WITH numbered AS (
    SELECT
        ROW_NUMBER() OVER (
            PARTITION BY wiki
            ORDER BY dt DESC
        ) AS row_num
    FROM
        event_sanitized.mediawikipingback
    WHERE
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) >= date_sub('$1', 23) AND
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2' AND
        (event.\`database\` LIKE 'mysql%' OR NOT (
            event.MediaWiki LIKE '1.31.0%' OR
            event.MediaWiki = '1.32.0-alpha'
        ))
)
SELECT
    '$1' AS \`date\`,
    COUNT(*) AS \`unique wiki count\`
FROM numbered
WHERE row_num = 1
;
" 2> /dev/null | grep -v parquet.hadoop
