#!/bin/bash
hive -e "
WITH numbered AS (
    SELECT
        event.OS AS event_os,
        ROW_NUMBER() OVER (
            PARTITION BY wiki
            ORDER BY dt DESC
        ) AS row_num
    FROM
        event_sanitized.mediawikipingback
    WHERE
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) >= date_sub('$1', 23) AND
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2' AND
        (event.\`database\` LIKE 'mysql%' OR NOT (
            event.MediaWiki LIKE '1.31.0%' OR
            event.MediaWiki = '1.32.0-alpha'
        )) AND
        event.OS != ''
)
SELECT
    '$1' AS date,
    SUM(IF(event_os LIKE 'Linux%', 1, 0)) AS \`Linux\`,
    SUM(IF(event_os LIKE 'WINNT%', 1, 0)) AS \`WINNT\`,
    SUM(IF(event_os LIKE 'Darwin%', 1, 0)) AS \`Darwin\`,
    SUM(IF(event_os LIKE 'FreeBSD%', 1, 0)) AS \`FreeBSD\`,
    SUM(IF(event_os LIKE 'SunOS%', 1, 0)) AS \`SunOS\`,
    SUM(IF(event_os LIKE 'CYGWIN%', 1, 0)) AS \`CYGWIN\`,
    SUM(IF(event_os LIKE 'NetBSD%', 1, 0)) AS \`NetBSD\`,
    SUM(IF(event_os LIKE 'OpenBSD%', 1, 0)) AS \`OpenBSD\`,
    SUM(IF(event_os NOT LIKE 'Linux%' AND
        event_os NOT LIKE 'WINNT%' AND
        event_os NOT LIKE 'Darwin%' AND
        event_os NOT LIKE 'FreeBSD%' AND
        event_os NOT LIKE 'SunOS%' AND
        event_os NOT LIKE 'CYGWIN%' AND
        event_os NOT LIKE 'NetBSD%' AND
        event_os NOT LIKE 'OpenBSD%', 1, 0)) AS \`Other\`
FROM numbered
WHERE row_num = 1
;
" 2> /dev/null | grep -v parquet.hadoop
