#!/bin/bash
hive -e "
WITH numbered AS (
    SELECT
        event.PHP AS event_php,
        event.MediaWiki AS event_mediawiki,
        ROW_NUMBER() OVER (
            PARTITION BY wiki
            ORDER BY dt DESC
        ) AS row_num
    FROM
        event_sanitized.mediawikipingback
    WHERE
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0'), 'T', LPAD(hour, 2, '0'))  >= '2017-03-29T17' AND
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2' AND
        (event.\`database\` LIKE 'mysql%' OR NOT (
            event.MediaWiki LIKE '1.31.0%' OR
            event.MediaWiki = '1.32.0-alpha'
        )) AND
        event.PHP != ''
)
SELECT
    '$1' AS date,
    SUM(IF(event_php LIKE '5.5%', 1, 0)) AS \`5.5\`,
    SUM(IF(event_php LIKE '5.6%', 1, 0)) AS \`5.6\`,
    SUM(IF(event_php LIKE '7.0%', 1, 0)) AS \`7.0\`,
    SUM(IF(event_php LIKE '7.1%', 1, 0)) AS \`7.1\`,
    SUM(IF(event_php LIKE '7.2%', 1, 0)) AS \`7.2\`,
    SUM(IF(event_php NOT LIKE '5.5%' AND
        event_php NOT LIKE '5.6%' AND
        event_php NOT LIKE '7.0%' AND
        event_php NOT LIKE '7.1%' AND
        event_php NOT LIKE '7.2%', 1, 0)) AS \`Other\`
FROM numbered
WHERE
    row_num = 1 AND
    event_mediawiki LIKE '$3%'
;
" 2> /dev/null | grep -v parquet.hadoop
