#!/bin/bash
hive -e "
WITH numbered AS (
    SELECT
        event.PHP AS event_php,
        event.MediaWiki AS event_mediawiki,
        ROW_NUMBER() OVER (
            PARTITION BY wiki
            ORDER BY dt DESC
        ) AS row_num
    FROM
        event_sanitized.mediawikipingback
    WHERE
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) >= date_sub('$1', 23) AND
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2' AND
        (event.\`database\` LIKE 'mysql%' OR NOT (
            event.MediaWiki LIKE '1.31.0%' OR
            event.MediaWiki = '1.32.0-alpha'
        )) AND
        event.PHP != ''
)
SELECT
    '$1' AS \`date\`,
    SUM(IF(event_php LIKE '5.5%', 1, 0)) AS \`5.5\`,
    SUM(IF(event_php LIKE '5.6%', 1, 0)) AS \`5.6\`,
    SUM(IF(event_php LIKE '7.0%', 1, 0)) AS \`7.0\`,
    SUM(IF(event_php LIKE '7.1%', 1, 0)) AS \`7.1\`,
    SUM(IF(event_php LIKE '7.2%', 1, 0)) AS \`7.2\`,
    SUM(IF(event_php LIKE '7.3%', 1, 0)) AS \`7.3\`,
    SUM(IF(event_php LIKE '7.4%', 1, 0)) AS \`7.4\`,
    SUM(IF(event_php LIKE '8.0%', 1, 0)) AS \`8.0\`,
    SUM(IF(event_php LIKE '8.1%', 1, 0)) AS \`8.1\`,
    SUM(IF(event_php LIKE '8.2%', 1, 0)) AS \`8.2\`,
    SUM(IF(event_php NOT LIKE '5.5%' AND
        event_php NOT LIKE '5.6%' AND
        event_php NOT LIKE '7.0%' AND
        event_php NOT LIKE '7.1%' AND
        event_php NOT LIKE '7.2%' AND
        event_php NOT LIKE '7.3%' AND
        event_php NOT LIKE '7.4%' AND
        event_php NOT LIKE '8.0%' AND
        event_php NOT LIKE '8.1%' AND
        event_php NOT LIKE '8.2%', 1, 0)) AS \`other\`
FROM numbered
WHERE
    row_num = 1 AND
    event_mediawiki LIKE '$3%'
;
" 2> /dev/null | grep -v parquet.hadoop
