#!/bin/bash
hive -e "
WITH numbered AS (
    SELECT
        event.serverSoftware AS event_serversoftware,
        ROW_NUMBER() OVER (
            PARTITION BY wiki
            ORDER BY dt DESC
        ) AS row_num
    FROM
        event_sanitized.mediawikipingback
    WHERE
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) >= date_sub('$1', 23) AND
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2' AND
        (event.\`database\` LIKE 'mysql%' OR NOT (
            event.MediaWiki LIKE '1.31.0%' OR
            event.MediaWiki = '1.32.0-alpha'
        )) AND
        event.serverSoftware != ''
)
SELECT
    '$1' AS report_date,
    SUM(IF(event_serversoftware LIKE 'Apache%', 1, 0)) AS \`Apache\`,
    SUM(IF(event_serversoftware LIKE 'Microsoft-IIS%', 1, 0)) AS \`Microsoft-IIS\`,
    SUM(IF(event_serversoftware LIKE 'nginx%', 1, 0)) AS \`nginx\`,
    SUM(IF(event_serversoftware LIKE 'lighttpd%', 1, 0)) AS \`lighttpd\`,
    SUM(IF(event_serversoftware LIKE 'LiteSpeed%', 1, 0)) AS \`LiteSpeed\`,
    SUM(IF(event_serversoftware NOT LIKE 'Apache%' AND
        event_serversoftware NOT LIKE 'Microsoft-IIS%' AND
        event_serversoftware NOT LIKE 'nginx%' AND
        event_serversoftware NOT LIKE 'lighttpd%' AND
        event_serversoftware NOT LIKE 'LiteSpeed%', 1, 0)) AS \`Other\`
FROM numbered
WHERE row_num = 1
;
" 2> /dev/null | grep -v parquet.hadoop
