#!/bin/bash
hive -e "
SET hive.mapred.mode = nonstrict;
SELECT
    '$1' AS date,
    SUM(IF(event.MediaWiki LIKE '1.28%', 1, 0)) AS \`1.28\`,
    SUM(IF(event.MediaWiki LIKE '1.29%', 1, 0)) AS \`1.29\`,
    SUM(IF(event.MediaWiki LIKE '1.30%', 1, 0)) AS \`1.30\`,
    SUM(IF(event.MediaWiki LIKE '1.31%', 1, 0)) AS \`1.31\`,
    SUM(IF(event.MediaWiki LIKE '1.32%', 1, 0)) AS \`1.32\`,
    SUM(IF(event.MediaWiki NOT LIKE '1.28%' AND
        event.MediaWiki NOT LIKE '1.29%' AND
        event.MediaWiki NOT LIKE '1.30%' AND
        event.MediaWiki NOT LIKE '1.31%' AND
        event.MediaWiki NOT LIKE '1.32%', 1, 0)) AS \`Other\`
FROM event.mediawikipingback AS alltime
JOIN (
    SELECT
        MAX(seqid) AS seqid
    FROM event.mediawikipingback
    WHERE
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2' AND
        (event.\`database\` LIKE 'mysql%' OR NOT (
            event.MediaWiki LIKE '1.31.0%' OR
            event.MediaWiki = '1.32.0-alpha'
        ))
    GROUP BY wiki
) AS latest
ON (alltime.seqid = latest.seqid)
WHERE
    event.MediaWiki != ''
;
" 2> /dev/null | grep -v parquet.hadoop
