#!/bin/bash
hive -e "
WITH numbered AS (
    SELECT
        event.MediaWiki AS event_mediawiki,
        ROW_NUMBER() OVER (
            PARTITION BY wiki
            ORDER BY dt DESC
        ) AS row_num
    FROM
        event_sanitized.mediawikipingback
    WHERE
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0'), 'T', LPAD(hour, 2, '0'))  >= '2017-03-29T17' AND
        CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2' AND
        (event.\`database\` LIKE 'mysql%' OR NOT (
            event.MediaWiki LIKE '1.31.0%' OR
            event.MediaWiki = '1.32.0-alpha'
        )) AND
        event.MediaWiki != ''
),
results AS (
    SELECT
        '$1' AS date,
        CASE
            WHEN event_mediawiki RLIKE '^[0-9]+\\.[0-9]+\\.[0-9]+\$'
                THEN event_mediawiki
            WHEN event_mediawiki RLIKE '^[0-9]+\\.[0-9]+\\.[0-9]+-wmf'
                THEN CONCAT(SUBSTR(event_mediawiki, 0, LOCATE('-wmf', event_mediawiki) - 1), ' (WMF)')
            WHEN event_mediawiki RLIKE '^[0-9]+\\.[0-9]+\\.[0-9]+-rc'
                THEN CONCAT(SUBSTR(event_mediawiki, 0, LOCATE('-rc', event_mediawiki) - 1), ' (RC)')
            WHEN event_mediawiki RLIKE '^[0-9]+\\.[0-9]+\\.[0-9]+-alpha'
                THEN CONCAT(SUBSTR(event_mediawiki, 0, LOCATE('-alpha', event_mediawiki) - 1), ' (ALPHA)')
            ELSE SUBSTR(event_mediawiki, 0, 6)
        END AS version
    FROM numbered
    WHERE row_num = 1
)
SELECT
    date,
    version,
    COUNT(*) as count
FROM results
GROUP BY
    date,
    version
ORDER BY count DESC
LIMIT 10000
;
" 2> /dev/null | grep -v parquet.hadoop
